version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  server:
    build: 
      context: ./patient-info-server
    container_name: server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/patientDB
    restart: always

  client:
    build: 
      context: ./patient-info-client
    container_name: client
    ports:
      - "3000:3000"
    restart: always

volumes:
  mongo-data:
    driver: local
